version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_weather
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  scraper:
    build:
      context: scraper/
      dockerfile: Dockerfile.scraper
    container_name: weather_scraper
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  api:
    # rebuild the api service to apply changes
    build:
      context: api/
      dockerfile: Dockerfile.api
    container_name: weather_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  frontend:
    image: nginx:latest
    container_name: weather_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

volumes:
  mongo-data: